import { useRef, useState } from 'react'
import { ArrowRight, Clipboard, Download, FileText, Moon, Plus, Sun, Trash2, Upload } from 'lucide-react'
import { useWorkspace, uid } from '../app/AppState'
import { addQuest } from '../domain/actions'
import { appStateSchema } from '../domain/schema'
import type { CvVariant, IncomeSource, Skill } from '../domain/model'
import { brand } from '../config/brand'
import { BulkImportPanel } from './bulk-import/BulkImportPanel'
import { buildCoachPrompt, parseCoachResponse, type CoachResponse } from './coach/coachExchange'

const today = () => new Date().toISOString()
const money = (amount: number, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount)

export function Onboarding({ onBack }: { onBack?: () => void }) {
  const { createProfile } = useWorkspace()
  const [name, setName] = useState('')
  const [title, setTitle] = useState('')
  return <main className="onboarding">{onBack && <button className="onboarding-back" onClick={onBack}>← Back to overview</button>}<section className="onboarding-card"><div className="brand-mark large">{brand.mark}</div><p className="eyebrow">{brand.eyebrow}</p><h1>Build your character.</h1><p className="lede">Not a fantasy avatar—the real you. Map what you know, choose what comes next, and turn growth into visible progress.</p><form onSubmit={(e) => { e.preventDefault(); if (name.trim()) createProfile({ name, title }) }}><label>Your name<input autoFocus required maxLength={80} value={name} onChange={(e) => setName(e.target.value)} placeholder="Kris"/></label><label>Current role or direction<input maxLength={100} value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Builder, analyst, designer…"/></label><button className="primary" type="submit">Open dashboard <ArrowRight size={18}/></button></form><small>Your data stays in this browser. No account required.</small></section></main>
}

function Empty({ text }: { text: string }) { return <p className="empty">{text}</p> }
function PageHead({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) { return <header className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{action}</header> }

export function SkillsPage() {
  const { state, update } = useWorkspace(); const [open, setOpen] = useState(false); if (!state) return null
  const profileId = state.activeProfileId
  function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const skill: Skill = { id: uid(), profileId, name: String(f.get('name')), category: String(f.get('category')), level: Number(f.get('level')), targetLevel: Number(f.get('target')), status: 'learning', evidence: String(f.get('evidence')) }; update((s) => ({ ...s, skills: [skill, ...s.skills] })); setOpen(false) }
  return <div className="page"><PageHead eyebrow="CAPABILITY INVENTORY" title="Skills" copy="Track ability with evidence—not vibes." action={<button className="primary" onClick={() => setOpen(!open)}><Plus size={18}/> Add skill</button>}/>{open && <form className="inline-form" onSubmit={add}><label>Skill name<input name="name" required/></label><label>Category<input name="category" placeholder="Technical, business…"/></label><label>Current level (1–10)<input name="level" type="number" min="1" max="10" defaultValue="3"/></label><label>Target level<input name="target" type="number" min="1" max="10" defaultValue="7"/></label><label className="wide">Evidence<textarea name="evidence" placeholder="Projects, outcomes, certificates…"/></label><button className="primary" type="submit">Save skill</button></form>}<div className="card-grid">{state.skills.map((skill) => <article className="panel skill-card" key={skill.id}><div className="panel-title"><div><span className="kind">{skill.category || 'General'}</span><h2>{skill.name}</h2></div><b className="skill-level">{skill.level}<small>/10</small></b></div><div className="meter"><i style={{ width: `${skill.level * 10}%` }}/><em style={{ left: `${skill.targetLevel * 10}%` }}/></div><p>{skill.evidence || 'No evidence added yet.'}</p><div className="row-actions"><select aria-label={`${skill.name} status`} value={skill.status} onChange={(e) => update((s) => ({ ...s, skills: s.skills.map((x) => x.id === skill.id ? { ...x, status: e.target.value as Skill['status'] } : x) }))}><option value="learning">Learning</option><option value="practicing">Practicing</option><option value="proven">Proven</option></select><button className="icon-btn" aria-label={`Delete ${skill.name}`} onClick={() => update((s) => ({ ...s, skills: s.skills.filter((x) => x.id !== skill.id) }))}><Trash2 size={17}/></button></div></article>)}</div>{!state.skills.length && <Empty text="Your skill map is empty. Start with one thing you can demonstrate."/>}</div>
}

export function CareerPage() {
  const { state, update } = useWorkspace(); const [tab, setTab] = useState<'money'|'cvs'>('money'); if (!state) return null
  const profileId = state.activeProfileId
  const currency = state.moneyPlan.currency
  function addIncome(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const x: IncomeSource = { id: uid(), profileId, name: String(f.get('name')), type: String(f.get('type')), monthlyAmount: Number(f.get('amount')), currency, active: true }; update((s) => ({ ...s, incomeSources: [x, ...s.incomeSources] })); e.currentTarget.reset() }
  function addCv(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const x: CvVariant = { id: uid(), profileId, name: String(f.get('name')), employer: String(f.get('employer')), role: String(f.get('role')), language: f.get('language') as CvVariant['language'], status: 'draft', fileName: String(f.get('fileName')), notes: '', updatedAt: today() }; update((s) => ({ ...s, cvs: [x, ...s.cvs] })); e.currentTarget.reset() }
  const total = state.incomeSources.filter((i) => i.active).reduce((sum, i) => sum + i.monthlyAmount, 0)
  return <div className="page"><PageHead eyebrow="CAREER & RESOURCES" title="Career" copy="See the work, money, and application assets behind your next move."/><div className="tabs"><button className={tab==='money'?'active':''} onClick={() => setTab('money')}>Income & plan</button><button className={tab==='cvs'?'active':''} onClick={() => setTab('cvs')}>CV vault</button></div>{tab === 'money' ? <><div className="metric-grid"><div className="metric"><span>Monthly income</span><b>{money(total, state.moneyPlan.currency)}</b></div><div className="metric"><span>Monthly target</span><input aria-label="Monthly target" type="number" min="0" value={state.moneyPlan.monthlyTarget} onChange={(e) => update((s) => ({ ...s, moneyPlan: { ...s.moneyPlan, monthlyTarget: Number(e.target.value) } }))}/></div><div className="metric"><span>Expenses</span><input aria-label="Monthly expenses" type="number" min="0" value={state.moneyPlan.monthlyExpenses} onChange={(e) => update((s) => ({ ...s, moneyPlan: { ...s.moneyPlan, monthlyExpenses: Number(e.target.value) } }))}/></div></div><form className="quick-add panel" onSubmit={addIncome}><input name="name" required placeholder="Income source" aria-label="Income source"/><input name="type" placeholder="Salary, freelance…" aria-label="Income type"/><input name="amount" required type="number" min="0" placeholder="Monthly amount" aria-label="Monthly amount"/><button className="primary"><Plus size={18}/> Add</button></form><div className="list-panel panel">{state.incomeSources.map((x) => <div className="income-row" key={x.id}><div><b>{x.name}</b><small>{x.type}</small></div><strong>{money(x.monthlyAmount, x.currency)}</strong><button className="icon-btn" aria-label={`Delete income source ${x.name}`} onClick={() => update((s) => ({ ...s, incomeSources: s.incomeSources.filter((i) => i.id !== x.id) }))}><Trash2 size={17}/></button></div>)}</div></> : <><form className="inline-form" onSubmit={addCv}><label>CV name<input name="name" required placeholder="Backend developer — EN"/></label><label>Employer<input name="employer"/></label><label>Role<input name="role"/></label><label>Language<select name="language"><option>English</option><option>Hungarian</option><option>Other</option></select></label><label>File name / link<input name="fileName"/></label><button className="primary"><Plus size={18}/> Track CV</button></form><div className="card-grid">{state.cvs.map((cv) => <article className="panel cv-card" key={cv.id}><FileText/><span className="kind">{cv.language}</span><h2>{cv.name}</h2><p>{cv.employer || 'General'} · {cv.role || 'Role not set'}</p><select aria-label={`Status for ${cv.name}`} value={cv.status} onChange={(e) => update((s) => ({ ...s, cvs: s.cvs.map((x) => x.id === cv.id ? { ...x, status: e.target.value as CvVariant['status'], updatedAt: today() } : x) }))}><option>draft</option><option>ready</option><option>sent</option><option>archived</option></select></article>)}</div></>}</div>
}

export function CoachPage() {
  const { state, update } = useWorkspace(); const [raw, setRaw] = useState(''); const [preview, setPreview] = useState<CoachResponse | null>(null); const [message, setMessage] = useState(''); if (!state) return null
  const profile = state.profiles.find((p) => p.id === state.activeProfileId) ?? state.profiles[0]
  const prompt = buildCoachPrompt({ profile: { name: profile.name, title: profile.title }, skills: state.skills.filter((item) => item.profileId === profile.id).map(({ name, level, targetLevel }) => ({ name, level, targetLevel })), currentGoals: state.quests.filter((q) => q.profileId === profile.id && q.status !== 'done').map((q) => q.title) })
  function parse() { const result = parseCoachResponse(raw); if (result.status === 'invalid') { setMessage(result.reason); setPreview(null) } else { setPreview(result.data); setMessage('Response validated. Review before importing.') } }
  function importItems() { if (!preview) return; update((s) => { let next = s; const advice = [...s.advice]; for (const item of preview.recommendations) { if (item.kind === 'quest' || item.kind === 'goal') next = addQuest(next, { title: item.title, notes: `${item.rationale}
Next: ${item.nextStep}`, priority: item.impact, status: 'next', xp: item.xp ?? 15 }); else advice.unshift({ id: uid(), profileId: s.activeProfileId, title: item.title, rationale: item.rationale, nextStep: item.nextStep, impact: item.impact, importedAt: today() }) } return { ...next, advice } }); setRaw(''); setPreview(null); setMessage('Imported into your workspace.') }
  return <div className="page"><PageHead eyebrow="PORTABLE AI WORKFLOW" title="AI Coach" copy="Use any AI you trust. You stay in control of what enters your workspace."/><div className="coach-grid"><section className="panel"><div className="step"><span>1</span><div><h2>Copy your context prompt</h2><p>It includes your current skills and Goals plus a strict response format.</p></div></div><textarea aria-label="AI context prompt" className="code-area" readOnly value={prompt}/><button className="primary" onClick={async () => { await navigator.clipboard?.writeText(prompt); setMessage('Prompt copied.') }}><Clipboard size={18}/> Copy prompt</button></section><section className="panel"><div className="step"><span>2</span><div><h2>Paste the AI response</h2><p>Nothing is imported until it passes validation and you confirm.</p></div></div><textarea aria-label="AI response JSON" className="code-area" value={raw} onChange={(e) => setRaw(e.target.value)} placeholder='{"schemaVersion":1,…}'/><button className="secondary" onClick={parse}>Validate response</button></section></div>{message && <p className="notice" role="status">{message}</p>}{state.advice.filter((item) => item.profileId === profile.id).length > 0 && <section className="panel preview"><p className="eyebrow">SAVED ADVICE</p>{state.advice.filter((item) => item.profileId === profile.id).map((item) => <article key={item.id}><span className={`status ${item.impact}`}>{item.impact}</span><div><b>{item.title}</b><p>{item.rationale}</p><small>Next: {item.nextStep}</small></div></article>)}</section>}{preview && <section className="panel preview"><p className="eyebrow">IMPORT PREVIEW</p><h2>{preview.summary}</h2>{preview.recommendations.map((r, i) => <article key={i}><span className={`status ${r.impact}`}>{r.impact}</span><div><b>{r.title}</b><p>{r.rationale}</p><small>Next: {r.nextStep}</small></div></article>)}<button className="primary" onClick={importItems}>Import {preview.recommendations.length} items</button></section>}</div>
}

export function ProfilePage() {
  const { state, update, reset, importState } = useWorkspace(); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(''); if (!state) return null
  const profile = state.profiles.find((p) => p.id === state.activeProfileId) ?? state.profiles[0]
  function exportData() { const exportState = { ...state!, cvs: state!.cvs.map(({ attachment, ...cv }) => ({ ...cv, fileName: attachment?.fileName ?? cv.fileName })) }; const blob = new Blob([JSON.stringify(exportState, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'untitled-workspace.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
  async function importFile(file?: File) { if (!file || file.size > 2_000_000) { setMessage('Choose a JSON export under 2 MB.'); return } try { const result = appStateSchema.safeParse(JSON.parse(await file.text())); if (!result.success) throw new Error(); importState(result.data); setMessage('Workspace imported.') } catch { setMessage('That file is not a valid workspace export.') } }
  async function resetWorkspace() { if (!confirm('Erase this workspace and every locally stored CV file from this browser?')) return; await reset() }
  async function wipeTestData() { if (!confirm('Wipe all test data and restart the app?')) return; const cleared = await reset(); if (cleared) window.location.reload() }
  return <div className="page"><PageHead eyebrow="CHARACTER & DATA" title="Profile" copy="Tune your identity and keep ownership of your data."/><section className="panel profile-editor"><div className="avatar huge">{profile.name.slice(0,2).toUpperCase()}</div><label>Display name<input required maxLength={80} value={profile.name} onChange={(e) => update((s) => ({ ...s, profiles: s.profiles.map((p) => p.id === profile.id ? { ...p, name: e.target.value } : p) }))}/></label><label>Role / direction<input maxLength={100} value={profile.title} onChange={(e) => update((s) => ({ ...s, profiles: s.profiles.map((p) => p.id === profile.id ? { ...p, title: e.target.value } : p) }))}/></label><label className="wide">Short bio<textarea maxLength={1000} value={profile.bio} onChange={(e) => update((s) => ({ ...s, profiles: s.profiles.map((p) => p.id === profile.id ? { ...p, bio: e.target.value } : p) }))}/></label></section><section className="panel data-panel"><div><h2>Appearance</h2><p>Switch between the Field Notes light theme and Night Console dark theme.</p></div><button className="secondary" onClick={() => update((s) => ({ ...s, theme: s.theme === 'dark' ? 'light' : 'dark' }))}>{state.theme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>} {state.theme === 'dark' ? 'Light mode' : 'Dark mode'}</button></section><section className="panel data-panel"><div><h2>Your data</h2><p>Export or restore workspace metadata, or erase this browser's workspace and CV files. JSON exports do not include the attached file contents yet.</p></div><div className="data-actions"><button className="secondary" onClick={exportData}><Download size={18}/> Export JSON</button><button className="secondary" onClick={() => input.current?.click()}><Upload size={18}/> Import JSON</button><input ref={input} hidden type="file" accept="application/json" onChange={(e) => importFile(e.target.files?.[0])}/><button className="danger" onClick={resetWorkspace}><Trash2 size={18}/> Reset workspace</button></div>{message && <p className="notice" role="status">{message}</p>}</section>{import.meta.env.DEV && <section className="panel data-panel dev-tools"><div><p className="eyebrow">DEVELOPMENT ONLY</p><h2>Testing reset</h2><p>Wipes the workspace and IndexedDB CV files, then reloads the onboarding screen. Console: <code>untitledDev.wipeAndRestart()</code></p></div><button className="danger" onClick={wipeTestData}><Trash2 size={18}/> Wipe test data & restart</button></section>}<BulkImportPanel/></div>
}
