import { useRef, useState } from 'react'
import { ArrowRight, BookOpen, Check, Clipboard, Download, FileText, Moon, Plus, Sparkles, Sun, Target, Trash2, Upload, WalletCards } from 'lucide-react'
import { useWorkspace, uid } from '../app/AppState'
import { addQuest, completeQuest } from '../domain/actions'
import { appStateSchema } from '../domain/schema'
import type { CvVariant, IncomeSource, LearningResource, Quest, Skill } from '../domain/model'
import { brand } from '../config/brand'
import { BulkImportPanel } from './bulk-import/BulkImportPanel'
import { buildCoachPrompt, parseCoachResponse, type CoachResponse } from './coach/coachExchange'

const today = () => new Date().toISOString()
const money = (amount: number, currency: string) => new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount)

export function Onboarding() {
  const { createProfile } = useWorkspace()
  const [name, setName] = useState('')
  const [title, setTitle] = useState('')
  return <main className="onboarding"><section className="onboarding-card"><div className="brand-mark large">{brand.mark}</div><p className="eyebrow">{brand.eyebrow}</p><h1>Build your character.</h1><p className="lede">Not a fantasy avatar—the real you. Map what you know, choose what comes next, and turn growth into visible progress.</p><form onSubmit={(e) => { e.preventDefault(); if (name.trim()) createProfile({ name, title }) }}><label>Your name<input autoFocus required maxLength={80} value={name} onChange={(e) => setName(e.target.value)} placeholder="Kris"/></label><label>Current role or direction<input maxLength={100} value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Builder, analyst, designer…"/></label><button className="primary" type="submit">Enter command center <ArrowRight size={18}/></button></form><small>Your data stays in this browser. No account required.</small></section></main>
}

export function Dashboard() {
  const { state, update } = useWorkspace(); if (!state) return null
  const profile = state.profiles.find((p) => p.id === state.activeProfileId) ?? state.profiles[0]
  const active = state.quests.filter((q) => q.status !== 'done').slice(0, 4)
  const income = state.incomeSources.filter((i) => i.active).reduce((sum, i) => sum + i.monthlyAmount, 0)
  const nextLevel = profile.level * 100
  return <div className="page"><header className="hero-header"><div><p className="eyebrow">COMMAND CENTER · LEVEL {profile.level}</p><h1>Good to see you, {profile.name}.</h1><p>Your next move matters more than the size of the map.</p></div><div className="level-orbit"><strong>{profile.level}</strong><span>LEVEL</span></div></header>
    <section className="progress-panel"><div><span>LEVEL PROGRESS</span><b>{profile.xp % 100} / 100 XP</b></div><progress value={profile.xp % 100} max={100}/><small>{nextLevel - profile.xp} XP until level {profile.level + 1}</small></section>
    <div className="dashboard-grid"><section className="panel span-2"><div className="panel-title"><div><p className="eyebrow">YOUR NEXT MOVE</p><h2>Active quests</h2></div><Target/></div>{active.length ? <div className="stack">{active.map((quest) => <div className="quest-row" key={quest.id}><button className="check" aria-label={`Complete ${quest.title}`} onClick={() => update((s) => completeQuest(s, quest.id))}><Check size={15}/></button><span><b>{quest.title}</b><small>{quest.priority} priority · +{quest.xp} XP</small></span><span className={`status ${quest.status}`}>{quest.status}</span></div>)}</div> : <Empty text="No active quests. Add one to define your next move."/>}</section>
    <section className="panel"><div className="panel-title"><div><p className="eyebrow">MONEY PULSE</p><h2>{money(income, state.moneyPlan.currency)}</h2></div><WalletCards/></div><p className="muted">active monthly income</p><div className="mini-metric"><span>Target</span><b>{money(state.moneyPlan.monthlyTarget, state.moneyPlan.currency)}</b></div><div className="mini-metric"><span>Expenses</span><b>{money(state.moneyPlan.monthlyExpenses, state.moneyPlan.currency)}</b></div></section>
    <section className="panel"><div className="panel-title"><div><p className="eyebrow">SKILL MAP</p><h2>{state.skills.length} mapped</h2></div><Sparkles/></div>{state.skills.length ? state.skills.slice(0, 4).map((skill) => <div className="skill-mini" key={skill.id}><span>{skill.name}</span><div><i style={{ width: `${skill.level * 10}%` }}/></div><b>{skill.level}</b></div>) : <Empty text="Add skills and evidence to see your map grow."/>}</section>
    <section className="panel span-2"><div className="panel-title"><div><p className="eyebrow">IN MOTION</p><h2>Learning queue</h2></div><BookOpen/></div>{state.resources.filter((r) => r.status !== 'completed').length ? state.resources.filter((r) => r.status !== 'completed').slice(0, 3).map((r) => <div className="resource-row" key={r.id}><span className="kind">{r.kind}</span><b>{r.title}</b><span>{r.status}</span></div>) : <Empty text="Queue a book, video, course, or anything worth learning from."/>}</section></div>
  </div>
}

function Empty({ text }: { text: string }) { return <p className="empty">{text}</p> }
function PageHead({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) { return <header className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{action}</header> }

export function SkillsPage() {
  const { state, update } = useWorkspace(); const [open, setOpen] = useState(false); if (!state) return null
  const profileId = state.activeProfileId
  function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const skill: Skill = { id: uid(), profileId, name: String(f.get('name')), category: String(f.get('category')), level: Number(f.get('level')), targetLevel: Number(f.get('target')), status: 'learning', evidence: String(f.get('evidence')) }; update((s) => ({ ...s, skills: [skill, ...s.skills] })); setOpen(false) }
  return <div className="page"><PageHead eyebrow="CAPABILITY INVENTORY" title="Skills" copy="Track ability with evidence—not vibes." action={<button className="primary" onClick={() => setOpen(!open)}><Plus size={18}/> Add skill</button>}/>{open && <form className="inline-form" onSubmit={add}><label>Skill name<input name="name" required/></label><label>Category<input name="category" placeholder="Technical, business…"/></label><label>Current level (1–10)<input name="level" type="number" min="1" max="10" defaultValue="3"/></label><label>Target level<input name="target" type="number" min="1" max="10" defaultValue="7"/></label><label className="wide">Evidence<textarea name="evidence" placeholder="Projects, outcomes, certificates…"/></label><button className="primary" type="submit">Save skill</button></form>}<div className="card-grid">{state.skills.map((skill) => <article className="panel skill-card" key={skill.id}><div className="panel-title"><div><span className="kind">{skill.category || 'General'}</span><h2>{skill.name}</h2></div><b className="skill-level">{skill.level}<small>/10</small></b></div><div className="meter"><i style={{ width: `${skill.level * 10}%` }}/><em style={{ left: `${skill.targetLevel * 10}%` }}/></div><p>{skill.evidence || 'No evidence added yet.'}</p><div className="row-actions"><select aria-label={`${skill.name} status`} value={skill.status} onChange={(e) => update((s) => ({ ...s, skills: s.skills.map((x) => x.id === skill.id ? { ...x, status: e.target.value as Skill['status'] } : x) }))}><option value="learning">Learning</option><option value="practicing">Practicing</option><option value="proven">Proven</option></select><button className="icon-btn" aria-label={`Delete ${skill.name}`} onClick={() => update((s) => ({ ...s, skills: s.skills.filter((x) => x.id !== skill.id) }))}><Trash2 size={17}/></button></div></article>)}</div>{!state.skills.length && <Empty text="Your skill map is empty. Start with one thing you can demonstrate."/>}</div>
}

export function QuestsPage() {
  const { state, update } = useWorkspace(); const [title, setTitle] = useState(''); if (!state) return null
  const groups: Quest['status'][] = ['now', 'next', 'later', 'done']
  return <div className="page"><PageHead eyebrow="ACTION SYSTEM" title="Quests" copy="Turn plans into small, finishable moves."/><form className="quick-add" onSubmit={(e) => { e.preventDefault(); if (!title.trim()) return; update((s) => addQuest(s, { title, priority: 'medium', status: 'now', xp: 15 })); setTitle('') }}><input aria-label="New quest" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="What is the next concrete action?"/><button className="primary" type="submit"><Plus size={18}/> Add</button></form><div className="kanban" tabIndex={0} aria-label="Quest board. Scroll horizontally to view all status columns.">{groups.map((group) => <section className="panel" key={group}><div className="column-title"><h2>{group}</h2><span>{state.quests.filter((q) => q.status === group).length}</span></div>{state.quests.filter((q) => q.status === group).map((q) => <article className="quest-card" key={q.id}><b>{q.title}</b><small>{q.priority} · +{q.xp} XP</small><div className="quest-controls"><select aria-label={`Status for ${q.title}`} value={q.status} onChange={(e) => update((s) => ({ ...s, quests: s.quests.map((x) => x.id === q.id ? { ...x, status: e.target.value as Quest['status'] } : x) }))}><option value="now">Now</option><option value="next">Next</option><option value="later">Later</option><option value="done">Done</option></select><select aria-label={`Priority for ${q.title}`} value={q.priority} onChange={(e) => update((s) => ({ ...s, quests: s.quests.map((x) => x.id === q.id ? { ...x, priority: e.target.value as Quest['priority'] } : x) }))}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div className="row-actions">{group !== 'done' && <button onClick={() => update((s) => completeQuest(s, q.id))}><Check size={15}/> Complete</button>}<button className="icon-btn" aria-label={`Delete ${q.title}`} onClick={() => update((s) => ({ ...s, quests: s.quests.filter((x) => x.id !== q.id) }))}><Trash2 size={15}/></button></div></article>)}</section>)}</div></div>
}

export function LibraryPage() {
  const { state, update } = useWorkspace(); const [open, setOpen] = useState(false); if (!state) return null
  const profileId = state.activeProfileId
  function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const item: LearningResource = { id: uid(), profileId, title: String(f.get('title')), kind: f.get('kind') as LearningResource['kind'], status: 'queued', creator: String(f.get('creator')), url: String(f.get('url')), notes: '' }; update((s) => ({ ...s, resources: [item, ...s.resources] })); setOpen(false) }
  return <div className="page"><PageHead eyebrow="LEARNING BACKLOG" title="Library" copy="Keep everything worth watching, reading, or practicing in one queue." action={<button className="primary" onClick={() => setOpen(!open)}><Plus size={18}/> Add resource</button>}/>{open && <form className="inline-form" onSubmit={add}><label>Title<input name="title" required/></label><label>Type<select name="kind"><option>book</option><option>video</option><option>course</option><option>article</option><option>podcast</option><option>other</option></select></label><label>Creator<input name="creator"/></label><label>Link<input name="url" type="url"/></label><button className="primary" type="submit">Add to queue</button></form>}<div className="list-panel panel">{state.resources.map((r) => <article className="library-item" key={r.id}><span className="resource-icon"><BookOpen size={19}/></span><div><span className="kind">{r.kind}</span><h2>{r.title}</h2><small>{r.creator}</small>{r.url && <a href={r.url} target="_blank" rel="noreferrer">Open resource</a>}</div><select aria-label={`${r.title} status`} value={r.status} onChange={(e) => update((s) => ({ ...s, resources: s.resources.map((x) => x.id === r.id ? { ...x, status: e.target.value as LearningResource['status'] } : x) }))}><option value="queued">Queued</option><option value="in-progress">In progress</option><option value="completed">Completed</option></select><button className="icon-btn" aria-label={`Delete ${r.title}`} onClick={() => update((s) => ({ ...s, resources: s.resources.filter((x) => x.id !== r.id) }))}><Trash2 size={17}/></button></article>)}{!state.resources.length && <Empty text="Nothing queued yet. Add the next thing you want to learn from."/>}</div><section className="panel knowledge-panel"><div className="panel-title"><div><p className="eyebrow">KNOWLEDGE BASE</p><h2>Knowledge notes</h2></div><span>{state.knowledgeNotes?.length ?? 0}</span></div>{(state.knowledgeNotes ?? []).map((note) => <article key={note.id}><h3>{note.title}</h3><p>{note.body}</p><div>{note.tags.map((tag) => <span className="kind" key={tag}>{tag}</span>)}</div></article>)}{!(state.knowledgeNotes?.length) && <Empty text="Knowledge notes imported through Bulk JSON will appear here."/>}</section></div>
}

export function CareerPage() {
  const { state, update } = useWorkspace(); const [tab, setTab] = useState<'money'|'cvs'>('money'); if (!state) return null
  const profileId = state.activeProfileId
  const currency = state.moneyPlan.currency
  function addIncome(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const x: IncomeSource = { id: uid(), profileId, name: String(f.get('name')), type: String(f.get('type')), monthlyAmount: Number(f.get('amount')), currency, active: true }; update((s) => ({ ...s, incomeSources: [x, ...s.incomeSources] })); e.currentTarget.reset() }
  function addCv(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const x: CvVariant = { id: uid(), profileId, name: String(f.get('name')), employer: String(f.get('employer')), role: String(f.get('role')), language: f.get('language') as CvVariant['language'], status: 'draft', fileName: String(f.get('fileName')), notes: '', updatedAt: today() }; update((s) => ({ ...s, cvs: [x, ...s.cvs] })); e.currentTarget.reset() }
  const total = state.incomeSources.filter((i) => i.active).reduce((sum, i) => sum + i.monthlyAmount, 0)
  return <div className="page"><PageHead eyebrow="CAREER & RESOURCES" title="Career" copy="See the work, money, and application assets behind your next move."/><div className="tabs"><button className={tab==='money'?'active':''} onClick={() => setTab('money')}>Income & plan</button><button className={tab==='cvs'?'active':''} onClick={() => setTab('cvs')}>CV vault</button></div>{tab === 'money' ? <><div className="metric-grid"><div className="metric"><span>Monthly income</span><b>{money(total, state.moneyPlan.currency)}</b></div><div className="metric"><span>Monthly target</span><input aria-label="Monthly target" type="number" min="0" value={state.moneyPlan.monthlyTarget} onChange={(e) => update((s) => ({ ...s, moneyPlan: { ...s.moneyPlan, monthlyTarget: Number(e.target.value) } }))}/></div><div className="metric"><span>Expenses</span><input aria-label="Monthly expenses" type="number" min="0" value={state.moneyPlan.monthlyExpenses} onChange={(e) => update((s) => ({ ...s, moneyPlan: { ...s.moneyPlan, monthlyExpenses: Number(e.target.value) } }))}/></div></div><form className="quick-add panel" onSubmit={addIncome}><input name="name" required placeholder="Income source" aria-label="Income source"/><input name="type" placeholder="Salary, freelance…" aria-label="Income type"/><input name="amount" required type="number" min="0" placeholder="Monthly amount" aria-label="Monthly amount"/><button className="primary"><Plus size={18}/> Add</button></form><div className="list-panel panel">{state.incomeSources.map((x) => <div className="income-row" key={x.id}><div><b>{x.name}</b><small>{x.type}</small></div><strong>{money(x.monthlyAmount, x.currency)}</strong><button className="icon-btn" aria-label={`Delete income source ${x.name}`} onClick={() => update((s) => ({ ...s, incomeSources: s.incomeSources.filter((i) => i.id !== x.id) }))}><Trash2 size={17}/></button></div>)}</div></> : <><form className="inline-form" onSubmit={addCv}><label>CV name<input name="name" required placeholder="Backend developer — EN"/></label><label>Employer<input name="employer"/></label><label>Role<input name="role"/></label><label>Language<select name="language"><option>English</option><option>Hungarian</option><option>Other</option></select></label><label>File name / link<input name="fileName"/></label><button className="primary"><Plus size={18}/> Track CV</button></form><div className="card-grid">{state.cvs.map((cv) => <article className="panel cv-card" key={cv.id}><FileText/><span className="kind">{cv.language}</span><h2>{cv.name}</h2><p>{cv.employer || 'General'} · {cv.role || 'Role not set'}</p><select aria-label={`Status for ${cv.name}`} value={cv.status} onChange={(e) => update((s) => ({ ...s, cvs: s.cvs.map((x) => x.id === cv.id ? { ...x, status: e.target.value as CvVariant['status'], updatedAt: today() } : x) }))}><option>draft</option><option>ready</option><option>sent</option><option>archived</option></select></article>)}</div></>}</div>
}

export function CoachPage() {
  const { state, update } = useWorkspace(); const [raw, setRaw] = useState(''); const [preview, setPreview] = useState<CoachResponse | null>(null); const [message, setMessage] = useState(''); if (!state) return null
  const profile = state.profiles.find((p) => p.id === state.activeProfileId) ?? state.profiles[0]
  const prompt = buildCoachPrompt({ profile: { name: profile.name, title: profile.title }, skills: state.skills.filter((item) => item.profileId === profile.id).map(({ name, level, targetLevel }) => ({ name, level, targetLevel })), currentQuests: state.quests.filter((q) => q.profileId === profile.id && q.status !== 'done').map((q) => q.title) })
  function parse() { const result = parseCoachResponse(raw); if (result.status === 'invalid') { setMessage(result.reason); setPreview(null) } else { setPreview(result.data); setMessage('Response validated. Review before importing.') } }
  function importItems() { if (!preview) return; update((s) => { let next = s; const advice = [...s.advice]; for (const item of preview.recommendations) { if (item.kind === 'quest') next = addQuest(next, { title: item.title, notes: `${item.rationale}
Next: ${item.nextStep}`, priority: item.impact, status: 'next', xp: item.xp ?? 15 }); else advice.unshift({ id: uid(), profileId: s.activeProfileId, title: item.title, rationale: item.rationale, nextStep: item.nextStep, impact: item.impact, importedAt: today() }) } return { ...next, advice } }); setRaw(''); setPreview(null); setMessage('Imported into your workspace.') }
  return <div className="page"><PageHead eyebrow="PORTABLE AI WORKFLOW" title="AI Coach" copy="Use any AI you trust. You stay in control of what enters your workspace."/><div className="coach-grid"><section className="panel"><div className="step"><span>1</span><div><h2>Copy your context prompt</h2><p>It includes your current skills and quests plus a strict response format.</p></div></div><textarea aria-label="AI context prompt" className="code-area" readOnly value={prompt}/><button className="primary" onClick={async () => { await navigator.clipboard?.writeText(prompt); setMessage('Prompt copied.') }}><Clipboard size={18}/> Copy prompt</button></section><section className="panel"><div className="step"><span>2</span><div><h2>Paste the AI response</h2><p>Nothing is imported until it passes validation and you confirm.</p></div></div><textarea aria-label="AI response JSON" className="code-area" value={raw} onChange={(e) => setRaw(e.target.value)} placeholder='{"schemaVersion":1,…}'/><button className="secondary" onClick={parse}>Validate response</button></section></div>{message && <p className="notice" role="status">{message}</p>}{state.advice.filter((item) => item.profileId === profile.id).length > 0 && <section className="panel preview"><p className="eyebrow">SAVED ADVICE</p>{state.advice.filter((item) => item.profileId === profile.id).map((item) => <article key={item.id}><span className={`status ${item.impact}`}>{item.impact}</span><div><b>{item.title}</b><p>{item.rationale}</p><small>Next: {item.nextStep}</small></div></article>)}</section>}{preview && <section className="panel preview"><p className="eyebrow">IMPORT PREVIEW</p><h2>{preview.summary}</h2>{preview.recommendations.map((r, i) => <article key={i}><span className={`status ${r.impact}`}>{r.impact}</span><div><b>{r.title}</b><p>{r.rationale}</p><small>Next: {r.nextStep}</small></div></article>)}<button className="primary" onClick={importItems}>Import {preview.recommendations.length} items</button></section>}</div>
}

export function ProfilePage() {
  const { state, update, reset, importState } = useWorkspace(); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(''); if (!state) return null
  const profile = state.profiles.find((p) => p.id === state.activeProfileId) ?? state.profiles[0]
  function exportData() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'untitled-workspace.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
  async function importFile(file?: File) { if (!file || file.size > 2_000_000) { setMessage('Choose a JSON export under 2 MB.'); return } try { const result = appStateSchema.safeParse(JSON.parse(await file.text())); if (!result.success) throw new Error(); importState(result.data); setMessage('Workspace imported.') } catch { setMessage('That file is not a valid workspace export.') } }
  return <div className="page"><PageHead eyebrow="CHARACTER & DATA" title="Profile" copy="Tune your identity and keep ownership of your data."/><section className="panel profile-editor"><div className="avatar huge">{profile.name.slice(0,2).toUpperCase()}</div><label>Display name<input required maxLength={80} value={profile.name} onChange={(e) => update((s) => ({ ...s, profiles: s.profiles.map((p) => p.id === profile.id ? { ...p, name: e.target.value } : p) }))}/></label><label>Role / direction<input maxLength={100} value={profile.title} onChange={(e) => update((s) => ({ ...s, profiles: s.profiles.map((p) => p.id === profile.id ? { ...p, title: e.target.value } : p) }))}/></label><label className="wide">Short bio<textarea maxLength={1000} value={profile.bio} onChange={(e) => update((s) => ({ ...s, profiles: s.profiles.map((p) => p.id === profile.id ? { ...p, bio: e.target.value } : p) }))}/></label></section><section className="panel data-panel"><div><h2>Appearance</h2><p>Switch between the Field Notes light theme and Night Console dark theme.</p></div><button className="secondary" onClick={() => update((s) => ({ ...s, theme: s.theme === 'dark' ? 'light' : 'dark' }))}>{state.theme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>} {state.theme === 'dark' ? 'Light mode' : 'Dark mode'}</button></section><section className="panel data-panel"><div><h2>Your data</h2><p>Export a portable backup, restore it later, or erase this browser's workspace.</p></div><div className="data-actions"><button className="secondary" onClick={exportData}><Download size={18}/> Export JSON</button><button className="secondary" onClick={() => input.current?.click()}><Upload size={18}/> Import JSON</button><input ref={input} hidden type="file" accept="application/json" onChange={(e) => importFile(e.target.files?.[0])}/><button className="danger" onClick={() => confirm('Erase this workspace from this browser?') && reset()}><Trash2 size={18}/> Reset workspace</button></div>{message && <p className="notice" role="status">{message}</p>}</section><BulkImportPanel/></div>
}
