import { expect, test } from '@playwright/test'

async function createCharacter(page: import('@playwright/test').Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Build your workspace' }).click()
  await page.getByLabel('Your name').fill('Kris')
  await page.getByLabel('Current role or direction').fill('Product Builder')
  await page.getByRole('button', { name: /open dashboard/i }).click()
  await expect(page.getByRole('heading', { name: /good to see you, kris/i })).toBeVisible()
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => {
    localStorage.clear()
    await Promise.all(['untitled.attachments.v1', 'untitled.achievement-images.v1'].map((databaseName) => new Promise<void>((resolve, reject) => {
      const request = indexedDB.deleteDatabase(databaseName)
      request.onsuccess = () => resolve()
      request.onerror = () => reject(request.error)
      request.onblocked = () => reject(new Error(`${databaseName} is blocked`))
    })))
  })
})

test('creates a persistent character and cannot farm XP by reopening a Goal', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Create goal' }).click()
  await page.getByLabel('Goal title').fill('Ship alpha')
  await page.getByRole('button', { name: 'Add goal' }).click()
  await expect(page.getByText('Ship alpha')).toBeVisible()
  await page.getByRole('button', { name: /Complete · \+15 XP/ }).click()
  await expect(page.getByText('15 XP claimed')).toBeVisible()
  await page.getByRole('button', { name: 'Reopen' }).click()
  await expect(page.getByText('XP claimed')).toBeVisible()
  await page.getByRole('button', { name: 'Complete again' }).click()
  await page.reload()
  await expect(page.getByText('15 XP across level 1')).toBeVisible()
})

test('calculates Goal XP from difficulty instead of accepting a custom reward', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Create goal' }).click()
  await expect(page.getByLabel('XP reward')).toHaveCount(0)
  await page.getByLabel('Goal title').fill('Meaningful multi-step outcome')
  await page.getByLabel('Difficulty').selectOption('medium')
  await page.getByRole('button', { name: 'Add goal' }).click()
  const goalCard = page.getByRole('heading', { name: 'Meaningful multi-step outcome' }).locator('xpath=ancestor::article')
  await expect(goalCard.getByText('medium', { exact: true })).toBeVisible()
  await expect(goalCard.getByText('+30 XP', { exact: true })).toBeVisible()
})

test('introduces the product before setup and keeps the landing page responsive', async ({ page }) => {
  for (const width of [320, 390, 768, 1280]) {
    await page.setViewportSize({ width, height: 820 })
    await page.goto('/')
    await expect(page.getByRole('heading', { name: /see where you are/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /your plans make more sense/i })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }

  await page.getByRole('button', { name: 'Preview dark atmosphere' }).click()
  await expect(page.locator('.studio-demo')).toHaveClass(/dark/)
  await page.getByRole('button', { name: 'Preview light atmosphere' }).click()
  await expect(page.locator('.studio-demo')).not.toHaveClass(/dark/)
  await page.getByRole('button', { name: 'Build your workspace' }).click()
  await expect(page.getByRole('heading', { name: /build your character/i })).toBeVisible()
  await page.getByRole('button', { name: /back to overview/i }).click()
  await expect(page.getByRole('heading', { name: /see where you are/i })).toBeVisible()
})

test('Dashboard links to source pages and directly manages Goals and learning', async ({ page }) => {
  await createCharacter(page)
  await expect(page.getByRole('button', { name: 'Dashboard', exact: true })).toHaveAttribute('aria-current', 'page')

  await page.getByLabel('Quick add goal').fill('Dashboard quest')
  await page.getByRole('button', { name: 'Add goal', exact: true }).click()
  await page.getByLabel('Plan for Dashboard quest').selectOption('next')
  await expect(page.getByLabel('Plan for Dashboard quest')).toHaveValue('next')
  await page.getByRole('button', { name: 'Complete Dashboard quest' }).click()
  await expect(page.getByText('Dashboard quest')).toHaveCount(0)

  await page.getByRole('button', { name: /Open Skills/ }).click()
  await expect(page.getByRole('heading', { name: 'Skills' })).toBeVisible()
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add resource' }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Dashboard learning item')
  await page.getByRole('button', { name: 'Add to Library' }).click()
  await page.getByRole('button', { name: 'Dashboard', exact: true }).first().click()
  await page.getByLabel('Learning status for Dashboard learning item').selectOption('completed')
  await expect(page.getByText('Dashboard learning item')).toHaveCount(0)

  await page.getByRole('button', { name: /Open Career/ }).click()
  await expect(page.getByRole('heading', { name: 'Career' })).toBeVisible()
})

test('a Goal pulls Library support and Library reflects Goal completion', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add resource' }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Architecture field guide')
  await page.getByRole('textbox', { name: 'Link', exact: true }).fill('https://example.com/architecture-guide')
  await page.getByRole('button', { name: 'Add to Library' }).click()

  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Create goal' }).click()
  await page.getByLabel('Goal title').fill('Design the new system')
  await page.getByLabel(/Architecture field guide/).check()
  await page.getByRole('button', { name: 'Add goal' }).click()
  const goalCard = page.getByRole('heading', { name: 'Design the new system' }).locator('xpath=ancestor::article')
  await expect(goalCard.getByText('Architecture field guide')).toBeVisible()
  await expect(goalCard.getByRole('link', { name: 'Open Architecture field guide' })).toHaveAttribute('href', 'https://example.com/architecture-guide')
  await page.getByRole('button', { name: 'Dashboard', exact: true }).first().click()
  await expect(page.getByRole('link', { name: 'Open Architecture field guide' })).toHaveAttribute('href', 'https://example.com/architecture-guide')
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await goalCard.getByRole('button', { name: /Complete · \+15 XP/ }).click()

  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  const resourceCard = page.getByRole('heading', { name: 'Architecture field guide' }).locator('xpath=ancestor::article')
  await expect(resourceCard.getByText('Goal completed')).toBeVisible()
  await expect(resourceCard.locator('.goal-impact small')).toHaveText('Design the new system')
  await expect(resourceCard.getByLabel('Architecture field guide status')).toHaveValue('queued')

  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Reopen' }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Architecture field guide' }).locator('xpath=ancestor::article').getByText('Goal completed')).toHaveCount(0)
})

test('keeps the completed Goal history bounded until the user loads more', async ({ page }) => {
  await createCharacter(page)
  await page.evaluate(() => {
    const key = 'untitled.workspace.v1'
    const state = JSON.parse(localStorage.getItem(key)!)
    state.quests = Array.from({ length: 10 }, (_, index) => ({
      id: `done-${index}`,
      profileId: state.activeProfileId,
      title: `Completed quest ${index + 1}`,
      notes: '',
      priority: 'medium',
      status: 'done',
      xp: 10,
      completedAt: new Date(Date.UTC(2026, 6, 14, 12, index)).toISOString(),
      xpAwardedAt: new Date(Date.UTC(2026, 6, 14, 12, index)).toISOString(),
    }))
    localStorage.setItem(key, JSON.stringify(state))
  })
  await page.reload()
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await expect(page.locator('.history-row')).toHaveCount(8)
  await page.getByRole('button', { name: /Load 8 more/ }).click()
  await expect(page.locator('.history-row')).toHaveCount(10)
})

test('adds a skill, learning resource, income source, and CV variant', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Skills', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add skill' }).click()
  await expect(page.getByRole('tab', { name: /AI assessment/ })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: /Manual/ }).click()
  await page.getByLabel('Skill name').fill('TypeScript')
  await page.getByLabel('Category').fill('Technical')
  await page.getByLabel('Include structured skill profile').check()
  await page.getByLabel('Assessment summary').fill('Reliable on routine typed frontend work with room to grow in advanced type design.')
  await page.getByLabel('Demonstrated strengths').fill('Builds typed React features independently\nDiagnoses common compiler errors')
  await page.getByLabel('Growth areas').fill('Advanced generics and library API design')
  await page.getByRole('button', { name: 'Save skill' }).click()
  await expect(page.getByRole('heading', { name: 'TypeScript' })).toBeVisible()
  await expect(page.getByText(/Reliable on routine typed frontend work/)).toBeVisible()
  await page.getByRole('button', { name: 'View full skill' }).click()
  await expect(page.getByText('Builds typed React features independently')).toBeVisible()
  await expect(page.getByText('Advanced generics and library API design')).toBeVisible()
  await page.getByRole('button', { name: 'Edit skill' }).click()
  await page.getByLabel('Skill name').fill('Advanced TypeScript')
  await page.getByLabel('Current level (1–10)').fill('6')
  await page.getByLabel('Experience').fill('Built and shipped a typed React application.')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('heading', { name: 'Advanced TypeScript' })).toBeVisible()

  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add resource' }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Effective TypeScript')
  await page.getByRole('button', { name: 'Add to Library' }).click()
  await expect(page.getByRole('heading', { name: 'Effective TypeScript' })).toBeVisible()

  await page.getByRole('button', { name: 'Career', exact: true }).first().click()
  await page.getByLabel('Monthly income target').fill('750000')
  await page.getByLabel('Income source name').click()
  await expect(page.getByLabel('Monthly income target')).toHaveValue('750,000')
  await page.getByLabel('Income source name').fill('Salary')
  await page.getByLabel('Monthly amount').fill('500000')
  await expect(page.getByLabel('Monthly amount')).toHaveValue('500,000')
  await page.getByRole('button', { name: 'Add income source' }).click()
  await expect(page.locator('.income-row strong')).toContainText(/500[,.\s]000/)
  await page.getByRole('button', { name: 'CV vault' }).click()
  await page.getByLabel('CV name').fill('Frontend CV — EN')
  await page.getByLabel('Language').selectOption('English')
  await page.getByRole('button', { name: 'Add to vault' }).click()
  await expect(page.getByRole('heading', { name: 'Frontend CV — EN' })).toBeVisible()
})

test('stores, reloads, downloads, and wipes an actual CV file', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Career', exact: true }).first().click()
  await page.getByRole('button', { name: 'CV vault' }).click()
  await page.getByLabel('CV name').fill('Local PDF CV')
  await page.getByLabel(/CV file/).setInputFiles({ name: 'kris-cv.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 local CV') })
  await page.getByRole('button', { name: 'Add to vault' }).click()
  await expect(page.getByText('kris-cv.pdf', { exact: true })).toBeVisible()
  await expect(page.getByText(/stored on this device/i)).toBeVisible()

  await page.reload()
  await page.getByRole('button', { name: 'Career', exact: true }).first().click()
  await page.getByRole('button', { name: 'CV vault' }).click()
  await expect(page.getByText('kris-cv.pdf', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('kris-cv.pdf')

  await page.getByRole('button', { name: 'Profile', exact: true }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Reset workspace' }).click()
  await expect(page.getByRole('heading', { name: /see where you are/i })).toBeVisible()
  const storedFiles = await page.evaluate(() => new Promise<number>((resolve, reject) => {
    const request = indexedDB.open('untitled.attachments.v1', 1)
    request.onerror = () => reject(request.error)
    request.onsuccess = () => {
      const transaction = request.result.transaction('cv-files', 'readonly')
      const count = transaction.objectStore('cv-files').count()
      count.onsuccess = () => resolve(count.result)
      count.onerror = () => reject(count.error)
    }
  }))
  expect(storedFiles).toBe(0)
})

test('validates and imports a portable AI response as a Goal', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'AI Coach', exact: true }).first().click()
  const response = JSON.stringify({ schemaVersion: 1, summary: 'Build evidence.', recommendations: [{ title: 'Publish a case study', rationale: 'Shows capability', nextStep: 'Draft the outline', impact: 'high', kind: 'goal', xp: 20 }] })
  await page.locator('textarea').nth(1).fill(response)
  await page.getByRole('button', { name: 'Validate response' }).click()
  await expect(page.getByRole('heading', { name: 'Build evidence.' })).toBeVisible()
  await page.getByRole('button', { name: 'Import 1 items' }).click()
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await expect(page.getByText('Publish a case study')).toBeVisible()
})

test('builds a truthful CV tuning prompt from recorded skill evidence', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Skills', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add skill' }).click()
  await page.getByRole('tab', { name: /Manual/ }).click()
  await page.getByLabel('Skill name').fill('Playwright')
  await page.getByLabel('Experience').fill('Built reliable dashboard filtering tests and found production defects.')
  await page.getByRole('button', { name: 'Save skill' }).click()

  await page.getByRole('button', { name: 'Career', exact: true }).first().click()
  await page.getByRole('button', { name: 'CV vault' }).click()
  await page.getByLabel('CV name').fill('QA CV')
  await page.getByLabel('Role').fill('Senior QA Engineer')
  await page.getByRole('button', { name: 'Add to vault' }).click()
  const cvCard = page.getByRole('heading', { name: 'QA CV' }).locator('xpath=ancestor::article')
  await cvCard.getByRole('button', { name: 'Tune with skills' }).click()
  await page.getByLabel(/Target role or job description/).fill('Senior QA role emphasizing Playwright automation')
  await page.getByRole('button', { name: 'Generate tuning prompt' }).click()
  await expect(page.getByLabel('Generated CV tuning prompt')).toContainText('Built reliable dashboard filtering tests')
  await expect(page.getByLabel('Generated CV tuning prompt')).toContainText('Never invent')
})

test('AI Coach imports a Library recommendation and connects it to a Goal', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Create goal' }).click()
  await page.getByLabel('Goal title').fill('Learn query optimization')
  await page.getByRole('button', { name: 'Add goal' }).click()

  await page.getByRole('button', { name: 'AI Coach', exact: true }).first().click()
  const response = JSON.stringify({ schemaVersion: 1, summary: 'Use one focused resource.', recommendations: [{ title: 'Use The Index, Luke', rationale: 'Directly supports query optimization.', nextStep: 'Read the indexing chapters.', impact: 'high', kind: 'library', resourceKind: 'article', creator: 'Markus Winand', url: 'https://use-the-index-luke.com/', supportsGoalTitle: 'Learn query optimization' }] })
  await page.getByLabel('AI response JSON').fill(response)
  await page.getByRole('button', { name: 'Validate response' }).click()
  await page.getByRole('button', { name: 'Import 1 items' }).click()
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  const resourceCard = page.getByRole('heading', { name: 'Use The Index, Luke' }).locator('xpath=ancestor::article')
  await expect(resourceCard).toContainText('Learn query optimization')
})

test('Skills embeds AI generation and progress-tracked assessment', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Skills', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add skill' }).click()
  await page.getByRole('tab', { name: /AI generate/ }).click()
  await page.getByLabel('What skills should the AI create?').fill('Add TypeScript based on my small React projects.')
  await page.getByRole('button', { name: 'Generate copy-paste prompt' }).click()
  await expect(page.getByLabel('Generated AI prompt')).toContainText('Return JSON only')

  const generated = JSON.stringify({ schemaVersion: 1, skills: [{ name: 'TypeScript', category: 'Technical', level: 3, targetLevel: 7, status: 'learning', evidence: 'Built small React projects.' }] })
  await page.getByLabel('AI response JSON').fill(generated)
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await expect(page.getByRole('heading', { name: '1 skills ready' })).toBeVisible()
  await page.getByRole('button', { name: 'Import 1 items' }).click()

  await page.getByRole('tab', { name: /AI assessment/ }).click()
  await page.getByLabel('Skill and context').fill('Assess my SQL skill.')
  await page.getByRole('button', { name: 'Generate copy-paste prompt' }).click()
  await expect(page.getByLabel('Generated AI prompt')).toContainText('Question 2 of 6')
  const assessed = JSON.stringify({ schemaVersion: 1, skill: { name: 'SQL', category: 'Data', level: 2, targetLevel: 6, status: 'learning', evidence: `Can write basic SELECT queries. ${'E'.repeat(700)}`, assessmentSummary: `Basic familiarity; joins and query planning are gaps. ${'S'.repeat(700)}`, strengths: ['Writes basic SELECT queries independently'], gaps: ['Needs practice with joins and query planning'] } })
  await page.getByLabel('AI response JSON').fill(assessed)
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await expect(page.getByRole('heading', { name: 'SQL: level 2/10' })).toBeVisible()
  await page.getByRole('button', { name: 'Import assessed skill' }).click()
  await expect(page.getByRole('status')).toContainText('Imported assessed skill')

  await expect(page.getByRole('heading', { name: 'TypeScript' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'SQL' })).toBeVisible()
  const sqlCard = page.getByRole('heading', { name: 'SQL' }).locator('xpath=ancestor::article')
  await expect(sqlCard.getByText('Assessment summary')).toBeVisible()
  await expect(sqlCard.getByText(/confidence/i)).toHaveCount(0)
  await sqlCard.getByRole('button', { name: 'View full skill' }).click()
  const skillDialog = page.getByRole('dialog', { name: 'SQL' })
  await expect(skillDialog.getByText('Writes basic SELECT queries independently')).toBeVisible()
  await expect(skillDialog.getByText('Needs practice with joins and query planning')).toBeVisible()
  await expect(skillDialog).toContainText('Can write basic SELECT queries')
  await skillDialog.getByRole('button', { name: 'Close', exact: true }).click()

  await page.getByRole('button', { name: 'List view' }).click()
  await expect(page.locator('.skill-list-row')).toHaveCount(2)
  const sqlRow = page.locator('.skill-list-row').filter({ hasText: 'SQL' })
  await sqlRow.getByRole('button', { name: 'View' }).click()
  await expect(page.getByRole('dialog', { name: 'SQL' })).toBeVisible()
  await page.getByRole('button', { name: 'Close skill details' }).click()
  page.once('dialog', async (dialog) => { expect(dialog.message()).toContain('Delete “SQL”?'); await dialog.dismiss() })
  await sqlRow.getByRole('button', { name: 'Delete SQL' }).click()
  await expect(sqlRow).toBeVisible()
  await page.getByRole('button', { name: 'Card view' }).click()
  await expect(page.getByRole('heading', { name: 'SQL' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'AI Profiler' })).toHaveCount(0)
})

test('Goals and Library embed their own portable AI generators', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Create goal' }).click()
  await page.getByRole('tab', { name: /AI generate/ }).click()
  await page.getByLabel('What goals should the AI create?').fill('Turn a portfolio launch into two concrete outcomes.')
  await page.getByRole('button', { name: 'Generate copy-paste prompt' }).click()
  await page.getByLabel('AI response JSON').fill(JSON.stringify({ schemaVersion: 1, quests: [{ title: 'Draft portfolio outline', notes: 'Define the sections.', priority: 'high', status: 'now', xp: 15 }] }))
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await page.getByRole('button', { name: 'Import 1 items' }).click()
  await expect(page.getByRole('heading', { name: 'Draft portfolio outline' })).toBeVisible()

  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add resource' }).click()
  await page.getByRole('tab', { name: /AI generate/ }).click()
  await page.getByLabel('What library items should the AI create?').fill('Add one TypeScript book for intermediate learners.')
  await page.getByRole('button', { name: 'Generate copy-paste prompt' }).click()
  await page.getByLabel('AI response JSON').fill(JSON.stringify({ schemaVersion: 1, resources: [{ title: 'Effective TypeScript', kind: 'book', status: 'queued', creator: 'Dan Vanderkam', url: '', notes: 'Focus on type design.' }] }))
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await page.getByRole('button', { name: 'Import 1 items' }).click()
  await expect(page.getByRole('heading', { name: 'Effective TypeScript' })).toBeVisible()
})

test('Goals contain Tasks and AI planning uses linked skill context with clipboard import', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await createCharacter(page)
  await page.getByRole('button', { name: 'Skills', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add skill' }).click()
  await page.getByRole('tab', { name: /Manual/ }).click()
  await page.getByLabel('Skill name').fill('Java')
  await page.getByLabel('Current level (1–10)').fill('4')
  await page.getByLabel('Experience').fill('Maintains routine Spring services and REST endpoints independently.')
  await page.getByRole('button', { name: 'Save skill' }).click()

  await page.getByRole('button', { name: 'Goals', exact: true }).first().click()
  await page.getByRole('button', { name: 'Create goal' }).click()
  await page.getByLabel('Goal title').fill('Improve Java skills')
  await page.getByLabel('Related skill').selectOption({ label: 'Java · level 4' })
  await page.getByRole('button', { name: 'Add goal' }).click()
  const goal = page.getByRole('heading', { name: 'Improve Java skills' }).locator('xpath=ancestor::article')
  await expect(goal).toBeVisible()
  await goal.getByRole('button', { name: 'Plan Tasks' }).click()
  await expect(page.getByRole('heading', { name: 'Tasks', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Add tasks' }).click()
  await page.getByLabel('Task title').fill('Build a small Spring endpoint')
  await page.getByRole('button', { name: 'Add Task' }).click()
  await expect(page.getByText('Build a small Spring endpoint')).toBeVisible()

  await page.getByRole('button', { name: 'Add tasks' }).click()
  await page.getByRole('tab', { name: /Plan with AI/ }).click()
  await page.getByRole('button', { name: 'Generate copy-paste prompt' }).click()
  await expect(page.getByText('No formatting work needed')).toBeVisible()
  await expect(page.getByLabel('Generated AI prompt')).toBeHidden()
  await page.getByText('Inspect generated prompt').click()
  await expect(page.getByLabel('Generated AI prompt')).toContainText('"level": 4')
  await expect(page.getByLabel('Generated AI prompt')).toContainText('Maintains routine Spring services')

  const result = JSON.stringify({ schemaVersion: 1, tasks: [{ title: 'Diagnose a concurrency bug', notes: 'Explain the race and verify the fix.', status: 'todo', goalTitle: 'Improve Java skills' }] })
  await page.evaluate((value) => navigator.clipboard.writeText(value), result)
  await page.getByRole('button', { name: 'Paste from clipboard' }).click()
  await expect(page.getByLabel('AI response JSON')).toHaveValue(result)
  await page.getByRole('button', { name: 'Validate & preview' }).click()
  await page.getByRole('button', { name: 'Import 1 items' }).click()
  await expect(page.getByText('Diagnose a concurrency bug')).toBeVisible()
})

for (const width of [320, 360, 390, 412, 768, 1024]) {
  test(`has no page overflow at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 820 })
    await createCharacter(page)
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(overflow).toBe(false)
  })
}

test('production runtime stays same-origin and reloads offline', async ({ page, context }) => {
  const crossOrigin: string[] = []
  page.on('request', (request) => {
    const url = new URL(request.url())
    if (url.origin !== 'http://127.0.0.1:4173') crossOrigin.push(request.url())
  })
  await createCharacter(page)
  await expect.poll(async () => page.evaluate(() => navigator.serviceWorker.ready.then(() => true))).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: /good to see you, kris/i })).toBeVisible()
  expect(crossOrigin).toEqual([])
})

test('mobile users can reach profile, data, and theme controls', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 820 })
  await createCharacter(page)
  await page.getByRole('button', { name: 'More', exact: true }).click()
  await page.getByRole('button', { name: 'Profile & data' }).click()
  await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export complete backup' })).toBeVisible()
  await expect(page.getByRole('button', { name: /mode/i })).toBeVisible()
})

test('invalid profile edits cannot make the workspace unloadable', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Profile', exact: true }).click()
  await page.getByLabel('Display name').fill('')
  await page.reload()
  await expect(page.getByRole('heading', { name: /good to see you, kris/i })).toBeVisible()
})

test('achievements keep project links and locally stored pictures after reload', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Achievements', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add achievement' }).click()
  await page.getByLabel('Achievement title').fill('Untitled workspace')
  await page.getByLabel('Link', { exact: true }).fill('example.com/project')
  await page.getByLabel('What makes it meaningful?').fill('A private tool built from the ground up.')
  await page.getByLabel('Picture').setInputFiles({ name: 'project.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64') })
  await page.getByRole('button', { name: 'Add achievement', exact: true }).last().click()
  await expect(page.getByRole('heading', { name: 'Untitled workspace' })).toBeVisible()
  await expect(page.getByRole('link', { name: /Open link/ })).toHaveAttribute('href', 'https://example.com/project')
  await expect(page.getByRole('img', { name: 'Untitled workspace achievement' })).toHaveAttribute('src', /^blob:/)
  await page.reload()
  await page.getByRole('button', { name: 'Achievements', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Untitled workspace' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Untitled workspace achievement' })).toHaveAttribute('src', /^blob:/)
})

test('complete backup restores profile data and actual CV files into an empty browser', async ({ page }) => {
  await createCharacter(page)
  await page.getByRole('button', { name: 'Skills', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add skill' }).click()
  await page.getByRole('tab', { name: /Manual/ }).click()
  await page.getByLabel('Skill name').fill('Backup skill')
  await page.getByLabel('Experience').fill('Evidence that must survive restore.')
  await page.getByRole('button', { name: 'Save skill' }).click()

  await page.getByRole('button', { name: 'Achievements', exact: true }).first().click()
  await page.getByRole('button', { name: 'Add achievement' }).click()
  await page.getByLabel('Achievement title').fill('Backup project')
  await page.getByLabel('Link', { exact: true }).fill('https://example.com/backup-project')
  await page.getByLabel('Picture').setInputFiles({ name: 'backup-project.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64') })
  await page.getByRole('button', { name: 'Add achievement', exact: true }).last().click()

  await page.getByRole('button', { name: 'Career', exact: true }).first().click()
  await page.getByRole('button', { name: 'CV vault' }).click()
  await page.getByLabel('CV name').fill('Backup CV')
  await page.getByLabel('CV file').setInputFiles({ name: 'backup-cv.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-restorable-content') })
  await page.getByRole('button', { name: 'Add to vault' }).click()

  await page.getByRole('button', { name: 'Profile', exact: true }).click()
  await expect(page.getByText('Bulk JSON import')).toHaveCount(0)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export complete backup' }).click()
  const backupDownload = await downloadPromise
  const backupPath = await backupDownload.path()
  expect(backupPath).toBeTruthy()

  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Reset workspace' }).click()
  await expect(page.getByRole('heading', { name: 'Build your character.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Restore complete backup' })).toBeVisible()
  await page.locator('.onboarding-card input[type="file"]').setInputFiles(backupPath!)
  await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()

  await page.getByRole('button', { name: 'Skills', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Backup skill' })).toBeVisible()
  await page.getByRole('button', { name: 'Achievements', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Backup project' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Backup project achievement' })).toHaveAttribute('src', /^blob:/)
  await expect(page.getByRole('link', { name: /Open link/ })).toHaveAttribute('href', 'https://example.com/backup-project')
  await page.getByRole('button', { name: 'Career', exact: true }).first().click()
  await page.getByRole('button', { name: 'CV vault' }).click()
  await expect(page.getByText('backup-cv.pdf')).toBeVisible()
  const restoredDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download' }).click()
  expect((await restoredDownloadPromise).suggestedFilename()).toBe('backup-cv.pdf')
})
