import { useState } from 'react'
import { ArrowDown, ArrowRight, BookOpen, Check, CheckCircle2, CircleUserRound, Compass, Database, FileText, Layers3, LockKeyhole, Moon, Sparkles, Sun, Target, TrendingUp, WalletCards } from 'lucide-react'
import { brand } from '../../config/brand'
import './landing.css'

function StudioPreview({ mode, onMode }: { mode: 'light' | 'dark'; onMode: (mode: 'light' | 'dark') => void }) {
  return <div className={`studio-demo ${mode}`} aria-label={`${mode} Dashboard preview`}>
    <div className="demo-window-bar"><div><i/><i/><i/></div><span>Untitled · Your private space</span><div className="demo-mode-switch" aria-label="Preview atmosphere"><button aria-label="Preview light atmosphere" aria-pressed={mode === 'light'} onClick={() => onMode('light')}><Sun size={13}/></button><button aria-label="Preview dark atmosphere" aria-pressed={mode === 'dark'} onClick={() => onMode('dark')}><Moon size={13}/></button></div></div>
    <div className="demo-workspace">
      <aside><span className="demo-mark">U/</span><div className="demo-nav active"><i/><b>Dashboard</b></div><div className="demo-nav"><i/><b>Goals</b></div><small>Grow</small><div className="demo-nav"><i/><b>Skills</b></div><div className="demo-nav"><i/><b>Library</b></div><small>Move</small><div className="demo-nav"><i/><b>Career</b></div><div className="demo-profile"><span>KR</span><b>Kris</b></div></aside>
      <section className="demo-main"><header><div><i/><b>Dashboard</b></div><small>Tuesday, July 14</small></header><article className="demo-welcome"><div><small>Your space, today</small><h3>Good to see you, Kris.</h3><p>2 goals have your attention right now.</p></div><div className="demo-progress"><span>3</span><div><small>Personal progress</small><b>64% into this level</b></div></div></article><div className="demo-grid"><article className="demo-focus"><small>Your next outcome</small><h4>What deserves your attention?</h4><div className="demo-add"><span>＋</span><p>Capture a meaningful goal…</p><b>Add goal</b></div>{['Publish the product case study', 'Finish the architecture proposal', 'Prepare the interview narrative'].map((goal, index) => <div className="demo-goal" key={goal}><Check size={11}/><span><b>{goal}</b><small>{index < 2 ? 'Now' : 'Next'}</small></span><i/></div>)}</article><article className="demo-capabilities"><small>Capabilities</small><h4>4 skills in view</h4>{[['Product strategy', 72], ['System design', 54], ['Facilitation', 63], ['TypeScript', 61]].map(([name, level]) => <div key={name}><b>{name}</b><i><em style={{ width: `${level}%` }}/></i></div>)}</article><article className="demo-money"><small>Monthly picture</small><h4>€4,200</h4><i><em/></i><span>76% of target</span></article><article className="demo-learning"><small>Learning in motion</small><h4>Resources with somewhere to go</h4><div><b>Designing Data-Intensive Applications</b><span>In progress</span></div><div><b>The Mom Test</b><span>Queued</span></div></article></div></section>
    </div>
  </div>
}

function GoalLibraryPreview() {
  return <div className="landing-link-preview"><section className="landing-goal-card"><div><span>Now</span><b>High priority</b></div><h3>Design the new system</h3><p>Turn the architecture into a decision the team can build from.</p><small><BookOpen size={13}/> Library support</small><article><BookOpen size={16}/><span><b>Architecture field guide</b><small>in progress</small></span></article></section><span className="landing-connection"><ArrowRight size={18}/></span><section className="landing-resource-card"><span>Book</span><h3>Architecture field guide</h3><div className="landing-impact"><CheckCircle2 size={17}/><span><b>Goal completed</b><small>Design the new system</small></span></div><small>Goal connection</small><p><Check size={13}/> Design the new system</p></section></div>
}

function SkillPreview() {
  return <div className="landing-skill-preview"><div className="landing-skill-head"><div><span>Product</span><h3>Product strategy</h3></div><b>7<small>/10</small></b></div><div className="landing-skill-meter"><i/><em/></div><section><small>Assessment summary</small><p>Leads discovery and roadmap decisions independently, with clear evidence across several releases.</p></section><details open><summary>Experience and growth areas</summary><div><p><Check size={13}/> Frames product decisions with customer evidence</p><p><Check size={13}/> Aligns teams around priorities and trade-offs</p><p><Target size={13}/> Strengthen portfolio-level strategy</p></div></details></div>
}

function AiPreview() {
  return <div className="landing-ai-preview"><div><span>1</span><section><small>Describe the outcome</small><b>Assess my SQL skill honestly.</b></section></div><div><span>2</span><section><small>Use any AI</small><p>Question 3 of 6 — how would you diagnose a slow query?</p></section></div><div><span>3</span><section><small>Review before importing</small><p>{'{ "level": 3, "strengths": […], "gaps": […] }'}</p></section></div></div>
}

export function LandingPage({ onStart }: { onStart: () => void }) {
  const [previewMode, setPreviewMode] = useState<'light' | 'dark'>('light')
  return <main className="landing-page">
    <nav className="landing-nav" aria-label="Landing navigation"><a className="landing-logo" href="#top"><span>{brand.mark}</span><div><b>{brand.productName}</b><small>Your private space</small></div></a><div className="landing-nav-links"><a href="#system">How it connects</a><a href="#ai">AI workflow</a><a href="#privacy">Privacy</a></div><button onClick={onStart}>Open your workspace <ArrowRight size={15}/></button></nav>

    <section className="landing-hero" id="top"><div className="landing-aura one"/><div className="landing-aura two"/><div className="landing-hero-copy"><p className="landing-kicker"><Sparkles size={14}/> A clearer way to grow</p><h1>See where you are. Decide where you’re going. Keep moving forward.</h1><p className="landing-lede">Bring your skills, Goals, learning, career, and finances into one private place—so you can focus on what matters next.</p><div className="landing-hero-actions"><button className="landing-cta" onClick={onStart}>Build your workspace <ArrowRight size={18}/></button><a href="#system">Explore the studio <ArrowDown size={15}/></a></div><div className="landing-proof"><span><LockKeyhole size={15}/> Local-first</span><span><CircleUserRound size={15}/> No account</span><span><Sparkles size={15}/> Bring your own AI</span></div></div><div className="landing-hero-visual"><StudioPreview mode={previewMode} onMode={setPreviewMode}/><span className="landing-float-card one"><Target size={15}/><b>Attention stays visible</b></span><span className="landing-float-card two"><TrendingUp size={15}/><b>Progress gains context</b></span></div></section>

    <section className="landing-trust"><p>One calm place for the parts of growth that usually live apart.</p><div><span>Skills</span><i/><span>Goals</span><i/><span>Library</span><i/><span>Career</span><i/><span>AI Coach</span></div></section>

    <section className="landing-section landing-system" id="system"><header><p className="landing-kicker"><Layers3 size={14}/> Context stays attached</p><h2>Your plans make more sense when the context stays attached.</h2><p>Untitled connects capability, outcomes, learning, and career reality instead of scattering them across disconnected apps.</p></header><div className="landing-bento"><article className="landing-bento-card goals"><span className="landing-card-icon"><Target/></span><p className="landing-card-label">Goals + Library</p><h3>Knowledge with a reason to exist.</h3><p>Pull books, courses, articles, and notes into a Goal. When the outcome is finished, the Library remembers what the resource helped accomplish.</p><GoalLibraryPreview/></article><article className="landing-bento-card skills"><span className="landing-card-icon"><TrendingUp/></span><p className="landing-card-label">Skill profiles</p><h3>Track experience, not self-image.</h3><p>Separate level rationale, real experience, demonstrated strengths, and growth areas into a profile you can revisit.</p><SkillPreview/></article><article className="landing-bento-card career"><span className="landing-card-icon"><WalletCards/></span><p className="landing-card-label">Career reality</p><h3>Keep ambition grounded.</h3><p>See income, targets, CV variants, and capability beside the work needed to change them.</p><div className="landing-career-metrics"><div><small>Monthly income</small><b>€4,200</b></div><div><small>Target</small><b>€5,500</b></div><div><small>CV vault</small><b>4 variants</b></div></div></article></div></section>

    <section className="landing-story-shell"><div className="landing-story"><div className="landing-story-copy"><p className="landing-kicker"><Compass size={14}/> From intention to evidence</p><h2>A simple loop that keeps growth moving.</h2><p>The app does not ask you to gamify your life. It helps you preserve the context between what you know, what you want, and what you actually finish.</p><ol><li><span>01</span><div><b>See what is true now</b><p>Record capability and the real experience behind it.</p></div></li><li><span>02</span><div><b>Choose where attention goes</b><p>Define a Goal and connect the knowledge that supports it.</p></div></li><li><span>03</span><div><b>Keep the evidence</b><p>Finish the outcome once and preserve what it says about your growth.</p></div></li></ol></div><div className="landing-loop-visual"><div className="landing-thread-map"><span className="thread-center">Your next<br/>move</span><span className="thread-node skills"><TrendingUp/>Skills</span><span className="thread-node goals"><Target/>Goals</span><span className="thread-node library"><BookOpen/>Library</span><span className="thread-node evidence"><FileText/>Evidence</span><i/><i/><i/><i/></div></div></div></section>

    <section className="landing-ai-section" id="ai"><div><p className="landing-kicker"><Sparkles size={14}/> AI without the lock-in</p><h2>Use the model you trust. Keep control of what enters.</h2><p>Generate a purpose-built prompt, use it with any AI, then validate and preview the structured response before importing. No hidden calls. No surprise writes.</p><ul><li><Check/>Progress-tracked skill assessment</li><li><Check/>Structured Goals and Library items</li><li><Check/>Explicit review before every import</li></ul></div><AiPreview/></section>

    <section className="landing-privacy" id="privacy"><div className="landing-privacy-icon"><Database/><LockKeyhole/></div><div><p className="landing-kicker">Your data stays yours</p><h2>Private by architecture, not by promise.</h2><p>Your workspace is stored locally in this browser. CV files stay on this device in IndexedDB. There is no account, analytics layer, remote font, or direct AI connection.</p></div><div className="landing-privacy-list"><span><b>Browser-local</b><small>Workspace data and preferences</small></span><span><b>Portable</b><small>Complete backup and validated restore</small></span><span><b>Resettable</b><small>Erase the workspace and stored files</small></span></div></section>

    <section className="landing-final"><div className="landing-final-orbit"><span>{brand.mark}</span></div><p className="landing-kicker">Start with what is true today</p><h2>Give your next chapter somewhere to take shape.</h2><p>No account. No setup ceremony. Create a private workspace and begin with the part of life that needs clarity now.</p><button className="landing-cta" onClick={onStart}>Create my workspace <ArrowRight size={18}/></button></section>
    <footer className="landing-footer"><a className="landing-logo" href="#top"><span>{brand.mark}</span><div><b>{brand.productName}</b><small>{brand.tagline}</small></div></a><p>Local-first · Account-free · Built for deliberate growth</p><button onClick={onStart}>Open app <ArrowRight size={14}/></button></footer>
  </main>
}
